[[eccodes]]
arch = "aarch64"
git-tree-sha1 = "886901f71e2f55a34a7af1fe9f3413ff864be107"
libgfortran_version = "5.0.0"
os = "macos"

    [[eccodes.download]]
    sha256 = "14cef971a0763f0d5b0d5a68d2d56ea1e2910009e6e446288727a588c26a6cea"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[eccodes]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b75b882f7eebcc8bf897b70998efd49dee6c95e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[eccodes.download]]
    sha256 = "fcd1af922df094dd929b744deda26ac6d8a82febd1a2a49dc673d357e91e113a"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[eccodes]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "716ea231a053c27d7ea86409c6610484cf215f1b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[eccodes.download]]
    sha256 = "dedac246c5e8907a00e127b02a693123bb10b43861f9d57df1f7203415a1fa49"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[eccodes]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae10fc40ac9d33d7689c4a68dd4184fe8f9bc2da"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[eccodes.download]]
    sha256 = "4a9ca40e5c0ce3e3f9d56c2b50e1eda74b314aaf0940ecf3151b603106c957a8"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[eccodes]]
arch = "x86_64"
git-tree-sha1 = "dc8d7dbbb5c8767c2110859192d80b534f7ef18d"
libgfortran_version = "5.0.0"
os = "macos"

    [[eccodes.download]]
    sha256 = "303b217f2b58b48b281c3f0eb22e78a9cdd28771d61687228ad112c2369e1275"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[eccodes]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cc8af946cab37dc3129ef1f258ddef4eff704e85"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[eccodes.download]]
    sha256 = "98fc63f05fd3a78a6903a42bb9439df9d37b8f8864083d408950edc8fdff0c26"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[eccodes]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76a5364d3069f62ff70f6d0466d4d7bc868b9669"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[eccodes.download]]
    sha256 = "97244eb0d5b6752aa38b72fb778f7780b1d71db1ab96df8dcfb9ce0ecfacf60b"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[eccodes]]
arch = "x86_64"
git-tree-sha1 = "1c4103ddaee3d383eeb9886cebf8a6b34f1559b3"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[eccodes.download]]
    sha256 = "94712e38afa22faf8fb606a8343b53b3d47d0e03ca313d45f706219e0feac8a4"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[eccodes]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44b30d96fcef6601dd53869cfb0b1dac327640ef"
libgfortran_version = "5.0.0"
os = "windows"

    [[eccodes.download]]
    sha256 = "0f19a26ef91d47fa55b7b4b4589cced064f0c031b3e60016f817468bcc1fb7f6"
    url = "https://github.com/JuliaBinaryWrappers/eccodes_jll.jl/releases/download/eccodes-v2.45.0+0/eccodes.v2.45.0.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
